from setuptools import setup, find_packages
setup(
    name='src',
    version='1.1.0',
    packages=find_packages(),
    
    install_requires=[
                        
                    'altgraph==0.17',
                    'cycler==0.12.0',
                    'distlib==0.3.9',
                    'docutils==0.20.1',
                    'filelock==3.16.1',
                    'fonttools==4.54.1',
                    'future==1.0.0',
                    'hidapi==0.14.0.post2',
                    'importlib-metadata==8.4.0',
                    'kiwisolver==1.4.7',
                    'markdown-it-py==3.0.0',
                    'matplotlib==3.5.3',
                    'mdurl==0.1.2',
                    'nh3==0.2.18',
                    'numpy==1.22.0',
                    'packaging==24.1',
                    'pefile==2024.8.26',
                    'pillow==10.4.0',
                    'pip==21.1.1',
                    'platformdirs==4.3.6',
                    'pygments==2.18.0',
                    'pyinstaller==6.10.0',
                    'pyinstaller-hooks-contrib==2024.8',
                    'pyparsing==3.1.4',
                    'pyqtgraph==0.13.3',
                    'pyserial==3.5',
                    'PySide2==5.15.2.1',
                    'pyTempico==1.0.0',
                    'python-dateutil==2.9.0.post0',
                    'pytz==2024.1',
                    'pywin32-ctypes==0.2.2',
                    'readme-renderer==43.0',
                    'rich==13.9.1',
                    'scipy==1.9.1 --only-binary=:all:',
                    'setuptools==65.5.1',
                    'shiboken2==5.15.2.1',
                    'six==1.16.0',
                    'typing-extensions==4.12.2',
                    'virtualenv==20.26.3',
                    'zipp==3.1.0',

    ],
    include_package_data=True, 
    package_data={
        '': ['Sources/*'], 
    },
)