# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CountHistBfTPQE.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import os


class Ui_CountsEstimated(object):
    """
    UI definition for the Estimated Counts tab.

    Generated by the Qt Designer UI compiler from 'CountHistBfTPQE.ui'.
    Builds the channel selection checkboxes, start/stop/clear buttons,
    graph display mode options, time range selector, and the counts/
    uncertainty table for channels A-D, plus a couple of manual helper
    methods (status color indicator, label font sizing) used by the
    logic layer that drives this tab.

    :param object: Base class placeholder used by the Qt UI compiler.
    """
    def setupUi(self, Form):
        """
        Builds and arranges every widget of the Estimated Counts tab.

        Mostly Qt Designer boilerplate (frames, layouts, size policies).
        Widget frame styling branches on `os.name` because macOS/Linux
        ("posix") render styled panel borders differently than Windows,
        so borders are disabled and margins removed on posix systems to
        keep a consistent look.

        :param Form: The QWidget/QDialog that will host this UI.
        :return: None
        """
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(941, 739)
        self.verticalLayout = QVBoxLayout(Form)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.GraphicSettingFrame = QFrame(Form)
        self.GraphicSettingFrame.setObjectName(u"GraphicSettingFrame")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.GraphicSettingFrame.sizePolicy().hasHeightForWidth())
        self.GraphicSettingFrame.setSizePolicy(sizePolicy)
        self.GraphicSettingFrame.setAutoFillBackground(True)
        self.GraphicSettingFrame.setFrameShape(QFrame.StyledPanel)
        self.GraphicSettingFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.GraphicSettingFrame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        
        self.SettingsFrame = QFrame(self.GraphicSettingFrame)
        self.SettingsFrame.setObjectName(u"SettingsFrame")
        
        sizePolicySettings= QSizePolicy(QSizePolicy.Preferred,QSizePolicy.Preferred)
        sizePolicySettings.setHorizontalStretch(4)
        sizePolicySettings.setVerticalStretch(0)
        sizePolicySettings.setHeightForWidth(self.SettingsFrame.sizePolicy().hasHeightForWidth())
        self.SettingsFrame.setFrameShape(QFrame.StyledPanel)
        self.SettingsFrame.setFrameShadow(QFrame.Plain)
        self.SettingsFrame.setSizePolicy(sizePolicySettings)
        self.verticalLayout_2 = QVBoxLayout(self.SettingsFrame)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.channelLabel = QLabel(self.SettingsFrame)
        self.channelLabel.setObjectName(u"channelLabel")

        self.verticalLayout_2.addWidget(self.channelLabel)

        self.frame_7 = QFrame(self.SettingsFrame)
        self.frame_7.setObjectName(u"frame_7")
        if os.name=="posix":
            self.frame_7.setFrameShape(QFrame.NoFrame)
            self.frame_7.setFrameShadow(QFrame.Plain)
            self.frame_7.setLineWidth(0)
            self.frame_7.setMidLineWidth(0)
        else:
            self.frame_7.setFrameShape(QFrame.StyledPanel)
            self.frame_7.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        if os.name=="posix":
            self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        else:
            self.horizontalLayout_3.setContentsMargins(8,4,8,4)

        defaultChannelCheckBoxSpacing = self.horizontalLayout_3.spacing()
        if defaultChannelCheckBoxSpacing <= 0:
            defaultChannelCheckBoxSpacing = 6
        self.horizontalLayout_3.setSpacing(max(1, defaultChannelCheckBoxSpacing // 2))
        self.channelACheckBox = QCheckBox(self.frame_7)

        self.horizontalLayout_3.addWidget(self.channelACheckBox)

        # NOTE: previously created/added as C-then-B (with their setText()
        # calls swapped to compensate), so the checkbox object named
        # channelBCheckBox displayed "C" and channelCCheckBox displayed
        # "B" — any code reading self.channelBCheckBox.isChecked() to mean
        # "channel B" was actually reading the checkbox the user sees
        # labelled "C". Creating/adding them in true A-B-C-D order fixes
        # that mismatch; see the corresponding setText() calls below.
        self.channelBCheckBox = QCheckBox(self.frame_7)
        self.channelBCheckBox.setObjectName(u"channelBCheckBox")

        self.horizontalLayout_3.addWidget(self.channelBCheckBox)

        self.channelCCheckBox = QCheckBox(self.frame_7)
        self.channelCCheckBox.setObjectName(u"channelCCheckBox")

        self.horizontalLayout_3.addWidget(self.channelCCheckBox)

        self.channelDCheckBox = QCheckBox(self.frame_7)
        self.channelDCheckBox.setObjectName(u"channelDCheckBox")

        self.horizontalLayout_3.addWidget(self.channelDCheckBox)


        self.verticalLayout_2.addWidget(self.frame_7)

        self.StartStopButtonsFrame = QFrame(self.SettingsFrame)
        self.StartStopButtonsFrame.setObjectName(u"StartStopButtonsFrame")
        
        if os.name=="posix":
            self.StartStopButtonsFrame.setFrameShape(QFrame.NoFrame)
            self.StartStopButtonsFrame.setFrameShadow(QFrame.Plain)
            self.StartStopButtonsFrame.setLineWidth(0)
            self.StartStopButtonsFrame.setMidLineWidth(0)
        else:
            self.StartStopButtonsFrame.setFrameShape(QFrame.StyledPanel)
            self.StartStopButtonsFrame.setFrameShadow(QFrame.Raised)


        self.horizontalLayout_4 = QHBoxLayout(self.StartStopButtonsFrame)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        if os.name=="posix":
            self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        else:
            self.horizontalLayout_4.setContentsMargins(8,4,8,4)
        self.startMeasurementButton = QPushButton(self.StartStopButtonsFrame)
        self.startMeasurementButton.setObjectName(u"startMeasurementButton")

        self.horizontalLayout_4.addWidget(self.startMeasurementButton)

        self.stopMeasurementButton = QPushButton(self.StartStopButtonsFrame)
        self.stopMeasurementButton.setObjectName(u"stopMeasurementButton")

        self.horizontalLayout_4.addWidget(self.stopMeasurementButton)
        self.TimeAndGraphFrame = QFrame(self.SettingsFrame)
        self.TimeAndGraphFrame.setObjectName(u"TimeAndGraphFrame")

        timeAndGraphSizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        timeAndGraphSizePolicy.setHeightForWidth(self.TimeAndGraphFrame.sizePolicy().hasHeightForWidth())
        self.TimeAndGraphFrame.setSizePolicy(timeAndGraphSizePolicy)

        if os.name=="posix":
            self.TimeAndGraphFrame.setFrameShape(QFrame.NoFrame)
            self.TimeAndGraphFrame.setFrameShadow(QFrame.Plain)
            self.TimeAndGraphFrame.setLineWidth(0)
            self.TimeAndGraphFrame.setMidLineWidth(0)
        else:
            self.TimeAndGraphFrame.setFrameShape(QFrame.StyledPanel)
            self.TimeAndGraphFrame.setFrameShadow(QFrame.Raised)
        self.gridLayoutTimeGraph = QGridLayout(self.TimeAndGraphFrame)
        self.gridLayoutTimeGraph.setObjectName(u"gridLayoutTimeGraph")

        if os.name=="posix":
            self.gridLayoutTimeGraph.setContentsMargins(0, 1, 0, 4)
        else:
            self.gridLayoutTimeGraph.setContentsMargins(8, 1, 8, 4)

        self.gridLayoutTimeGraph.setVerticalSpacing(12)

        self.timeRangeLabel = QLabel(self.TimeAndGraphFrame)
        self.timeRangeLabel.setObjectName(u"timeRangeLabel")
        self.gridLayoutTimeGraph.addWidget(self.timeRangeLabel, 0, 0)

        self.comboBoxTimeRange = QComboBox(self.TimeAndGraphFrame)
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.addItem("")
        self.comboBoxTimeRange.setObjectName(u"comboBoxTimeRange")

        comboBoxSizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        comboBoxSizePolicy.setHorizontalStretch(5)
        comboBoxSizePolicy.setVerticalStretch(0)
        comboBoxSizePolicy.setHeightForWidth(self.comboBoxTimeRange.sizePolicy().hasHeightForWidth())
        self.comboBoxTimeRange.setSizePolicy(comboBoxSizePolicy)
        self.gridLayoutTimeGraph.addWidget(self.comboBoxTimeRange, 0, 1)

        self.graphLabel = QLabel(self.TimeAndGraphFrame)
        self.graphLabel.setObjectName(u"graphLabel")
        self.gridLayoutTimeGraph.addWidget(self.graphLabel, 1, 0)


        self.graphModeComboBox = QComboBox(self.TimeAndGraphFrame)
        self.graphModeComboBox.setObjectName(u"graphModeComboBox")
        self.graphModeComboBox.addItem("")
        self.graphModeComboBox.addItem("")
        self.graphModeComboBox.addItem("")
        self.graphModeComboBox.setSizePolicy(comboBoxSizePolicy)
        self.gridLayoutTimeGraph.addWidget(self.graphModeComboBox, 1, 1)

        self.gridLayoutTimeGraph.setColumnStretch(1, 1)

        self.verticalLayout_2.addWidget(self.TimeAndGraphFrame)

        self.tableLabel= QLabel(self.SettingsFrame)
        self.tableLabel.setText("Detached:")
        self.verticalLayout_2.addWidget(self.tableLabel)


        self.tableDeatachedFrame = QFrame(self.SettingsFrame)
        self.verticalLayout_2.addWidget(self.tableDeatachedFrame)

        self.horizontalLayoutDeatached = QHBoxLayout(self.tableDeatachedFrame)
        if os.name=="posix":
            self.horizontalLayoutDeatached.setContentsMargins(0, 0, 0, 0) 
        else:
            self.horizontalLayoutDeatached.setContentsMargins(8,1,8,1)

        self.tableCheckBox = QCheckBox(self.tableDeatachedFrame)
        self.tableCheckBox.setText("Table")
        self.horizontalLayoutDeatached.addWidget(self.tableCheckBox)

        self.labelCheckBox = QCheckBox()
        self.labelCheckBox.setText("Current measurement")
        self.horizontalLayoutDeatached.addWidget(self.labelCheckBox)

        self.clearLabel = QLabel(self.SettingsFrame)
        self.clearLabel.setObjectName(u"clearLabel")

        self.verticalLayout_2.addWidget(self.clearLabel)

        self.ChannelABButtonFrame = QFrame(self.SettingsFrame)
        self.ChannelABButtonFrame.setObjectName(u"ChannelABButtonFrame")
        if os.name=="posix":
            self.ChannelABButtonFrame.setFrameShape(QFrame.NoFrame)
            self.ChannelABButtonFrame.setFrameShadow(QFrame.Plain)
            self.ChannelABButtonFrame.setLineWidth(0)
            self.ChannelABButtonFrame.setMidLineWidth(0)
        else:
            self.ChannelABButtonFrame.setFrameShape(QFrame.StyledPanel)
            self.ChannelABButtonFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.ChannelABButtonFrame)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        if os.name=="posix":
            self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        else:
            self.horizontalLayout_7.setContentsMargins(8,4,8,4)
        self.channelAClearButton = QPushButton(self.ChannelABButtonFrame)
        self.channelAClearButton.setObjectName(u"channelAClearButton")

        self.horizontalLayout_7.addWidget(self.channelAClearButton)

        self.channelBClearButton = QPushButton(self.ChannelABButtonFrame)
        self.channelBClearButton.setObjectName(u"channelBClearButton")

        self.horizontalLayout_7.addWidget(self.channelBClearButton)

        self.channelCClearButton = QPushButton(self.ChannelABButtonFrame)
        self.channelCClearButton.setObjectName(u"channelCClearButton")

        self.horizontalLayout_7.addWidget(self.channelCClearButton)

        self.channelDClearButton = QPushButton(self.ChannelABButtonFrame)
        self.channelDClearButton.setObjectName(u"channelDClearButton")

        self.horizontalLayout_7.addWidget(self.channelDClearButton)


        self.verticalLayout_2.addWidget(self.ChannelABButtonFrame)
        
        self.verticalLayout_2.addWidget(self.StartStopButtonsFrame)

        self.SaveDataPlotsFrame = QFrame(self.SettingsFrame)
        self.SaveDataPlotsFrame.setObjectName(u"SaveDataPlotsFrame")
        if os.name=="posix":
            self.SaveDataPlotsFrame.setFrameShape(QFrame.NoFrame)
            self.SaveDataPlotsFrame.setFrameShadow(QFrame.Plain)
            self.SaveDataPlotsFrame.setLineWidth(0)
            self.SaveDataPlotsFrame.setMidLineWidth(0)
        else:
            self.SaveDataPlotsFrame.setFrameShape(QFrame.StyledPanel)
            self.SaveDataPlotsFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.SaveDataPlotsFrame)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        if os.name=="posix":
            self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        else:
            self.horizontalLayout_9.setContentsMargins(8,4,8,4)
        self.saveDataButton = QPushButton(self.SaveDataPlotsFrame)
        self.saveDataButton.setObjectName(u"saveDataButton")

        self.horizontalLayout_9.addWidget(self.saveDataButton)

        self.savePlotsButton = QPushButton(self.SaveDataPlotsFrame)
        self.savePlotsButton.setObjectName(u"savePlotsButton")

        self.horizontalLayout_9.addWidget(self.savePlotsButton)


        self.verticalLayout_2.addWidget(self.SaveDataPlotsFrame)

        self.horizontalLayout.addWidget(self.SettingsFrame)

        self.GraphicsFrame = QFrame(self.GraphicSettingFrame)
        self.GraphicsFrame.setObjectName(u"GraphicsFrame")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(6)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.GraphicsFrame.sizePolicy().hasHeightForWidth())
        self.GraphicsFrame.setSizePolicy(sizePolicy3)
        self.GraphicsFrame.setFrameShape(QFrame.StyledPanel)
        self.GraphicsFrame.setFrameShadow(QFrame.Plain)

        self.horizontalLayout.addWidget(self.GraphicsFrame)


        self.verticalLayout.addWidget(self.GraphicSettingFrame)

        self.CountTableFrame = QFrame(Form)
        self.CountTableFrame.setObjectName(u"CountTableFrame")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(2)
        sizePolicy4.setHeightForWidth(self.CountTableFrame.sizePolicy().hasHeightForWidth())
        self.CountTableFrame.setSizePolicy(sizePolicy4)
        self.CountTableFrame.setAutoFillBackground(True)
        self.CountTableFrame.setFrameShape(QFrame.StyledPanel)
        self.CountTableFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.CountTableFrame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.scrollArea= QScrollArea(self.CountTableFrame)
        sizePolicyScrollArea= QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicyScrollArea.setHorizontalStretch(4)
        sizePolicyScrollArea.setVerticalStretch(3)
        sizePolicyScrollArea.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setSizePolicy(sizePolicyScrollArea)
        self.scrollArea.setFrameShape(QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QFrame.Plain)
        self.CountsFrame = QFrame(self.scrollArea)
        self.CountsFrame.setObjectName(u"CountsFrame")
        sizePolicy5 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy5.setHorizontalStretch(4)
        sizePolicy5.setVerticalStretch(3)
        sizePolicy5.setHeightForWidth(self.CountsFrame.sizePolicy().hasHeightForWidth())
        self.CountsFrame.setSizePolicy(sizePolicy5)
        self.verticalLayout_3 = QVBoxLayout(self.CountsFrame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.TitleCountsFrame = QFrame(self.CountsFrame)
        self.TitleCountsFrame.setObjectName(u"TitleCountsFrame")
        self.TitleCountsFrame.setFrameShape(QFrame.StyledPanel)
        self.TitleCountsFrame.setFrameShadow(QFrame.Raised)
        self.TitleCountsFrame.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        self.horizontalLayout_10 = QHBoxLayout(self.TitleCountsFrame)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.titleCounts = QLabel(self.TitleCountsFrame)
        self.titleCounts.setObjectName(u"titleCounts")

        self.horizontalLayout_10.addWidget(self.titleCounts)

        self.titleUncertainty = QLabel(self.TitleCountsFrame)
        self.titleUncertainty.setObjectName(u"titleUncertainty")

        self.horizontalLayout_10.addWidget(self.titleUncertainty)


        self.verticalLayout_3.addWidget(self.TitleCountsFrame)

        self.ChannelACountValues = QFrame(self.CountsFrame)
        self.ChannelACountValues.setObjectName(u"ChannelACountValues")
        self.ChannelACountValues.setFrameShape(QFrame.StyledPanel)
        self.ChannelACountValues.setFrameShadow(QFrame.Raised)
        self.ChannelACountValues.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        self.horizontalLayout_11 = QHBoxLayout(self.ChannelACountValues)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.channelAValuesCount = QLabel(self.ChannelACountValues)
        self.channelAValuesCount.setObjectName(u"channelAValuesCount")

        self.horizontalLayout_11.addWidget(self.channelAValuesCount)

        self.channelAUncertaintyCount = QLabel(self.ChannelACountValues)
        self.channelAUncertaintyCount.setObjectName(u"channelAUncertaintyCount")

        self.horizontalLayout_11.addWidget(self.channelAUncertaintyCount)


        self.verticalLayout_3.addWidget(self.ChannelACountValues)

        self.ChannelBCountValues = QFrame(self.CountsFrame)
        self.ChannelBCountValues.setObjectName(u"ChannelBCountValues")
        self.ChannelBCountValues.setFrameShape(QFrame.StyledPanel)
        self.ChannelBCountValues.setFrameShadow(QFrame.Raised)
        self.ChannelBCountValues.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        self.horizontalLayout_12 = QHBoxLayout(self.ChannelBCountValues)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.channelBValuesCount = QLabel(self.ChannelBCountValues)
        self.channelBValuesCount.setObjectName(u"channelBValuesCount")

        self.horizontalLayout_12.addWidget(self.channelBValuesCount)

        self.channelBUncertaintyCount = QLabel(self.ChannelBCountValues)
        self.channelBUncertaintyCount.setObjectName(u"channelBUncertaintyCount")

        self.horizontalLayout_12.addWidget(self.channelBUncertaintyCount)


        self.verticalLayout_3.addWidget(self.ChannelBCountValues)

        self.ChannelCCountValues = QFrame(self.CountsFrame)
        self.ChannelCCountValues.setObjectName(u"ChannelCCountValues")
        self.ChannelCCountValues.setFrameShape(QFrame.StyledPanel)
        self.ChannelCCountValues.setFrameShadow(QFrame.Raised)
        self.ChannelCCountValues.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        self.horizontalLayout_13 = QHBoxLayout(self.ChannelCCountValues)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.channelCValuesCount = QLabel(self.ChannelCCountValues)
        self.channelCValuesCount.setObjectName(u"channelCValuesCount")

        self.horizontalLayout_13.addWidget(self.channelCValuesCount)

        self.channelCUncertaintyCount = QLabel(self.ChannelCCountValues)
        self.channelCUncertaintyCount.setObjectName(u"channelCUncertaintyCount")

        self.horizontalLayout_13.addWidget(self.channelCUncertaintyCount)


        self.verticalLayout_3.addWidget(self.ChannelCCountValues)

        self.ChannelDCountValues = QFrame(self.CountsFrame)
        self.ChannelDCountValues.setObjectName(u"ChannelDCountValues")
        self.ChannelDCountValues.setFrameShape(QFrame.StyledPanel)
        self.ChannelDCountValues.setFrameShadow(QFrame.Raised)
        self.ChannelDCountValues.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        self.horizontalLayout_14 = QHBoxLayout(self.ChannelDCountValues)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.channelDValuesCount = QLabel(self.ChannelDCountValues)
        self.channelDValuesCount.setObjectName(u"channelDValuesCount")

        self.horizontalLayout_14.addWidget(self.channelDValuesCount)

        self.channelDUncertaintyCount = QLabel(self.ChannelDCountValues)
        self.channelDUncertaintyCount.setObjectName(u"channelDUncertaintyCount")

        self.horizontalLayout_14.addWidget(self.channelDUncertaintyCount)


        self.verticalLayout_3.addWidget(self.ChannelDCountValues)


        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.scrollArea.setWidget(self.CountsFrame)

        self.TableFrame = QFrame(self.CountTableFrame)
        self.TableFrame.setObjectName(u"TableFrame")
        sizePolicy6 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy6.setHorizontalStretch(6)
        sizePolicy6.setVerticalStretch(9)
        sizePolicy6.setHeightForWidth(self.TableFrame.sizePolicy().hasHeightForWidth())
        self.TableFrame.setSizePolicy(sizePolicy6)
        self.TableFrame.setFrameShape(QFrame.StyledPanel)
        self.TableFrame.setFrameShadow(QFrame.Plain)
        self.horizontalLayout_15 = QVBoxLayout(self.TableFrame)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        #Table with the count history: one row per sample, one column per channel
        self.countValuesTable = QTableWidget(self.TableFrame)
        if (self.countValuesTable.columnCount() < 5):
            self.countValuesTable.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.countValuesTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.countValuesTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.countValuesTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.countValuesTable.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.countValuesTable.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.countValuesTable.setObjectName(u"countValuesTable")
        self.countValuesTable.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.countValuesTable.setAlternatingRowColors(False)
        self.countValuesTable.setShowGrid(True)
        self.countValuesTable.setSortingEnabled(False)
        self.countValuesTable.horizontalHeader().setVisible(True)
        self.countValuesTable.horizontalHeader().setCascadingSectionResizes(False)
        self.countValuesTable.horizontalHeader().setProperty("showSortIndicator", False)
        self.countValuesTable.horizontalHeader().setStretchLastSection(True)
        self.countValuesTable.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.countValuesTable.setEditTriggers(QAbstractItemView.NoEditTriggers)


       
        self.statusFrame=QFrame(self.TableFrame)
        self.statusFrame.setFrameShape(QFrame.StyledPanel)
        self.statusFrame.setFrameShadow(QFrame.Plain)
        self.statusLayout = QHBoxLayout(self.statusFrame)
        sizePolicyStatus = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicyStatus.setHorizontalStretch(6)
        sizePolicyStatus.setVerticalStretch(1)
        sizePolicyStatus.setHeightForWidth(self.statusFrame.sizePolicy().hasHeightForWidth())
        self.statusFrame.setSizePolicy(sizePolicyStatus)

        # Create Labels
        self.labelStatus = QLabel("Status:", self.statusFrame)
        self.labelState = QLabel("No running", self.statusFrame)
        self.labelColor = QLabel("N", self.statusFrame)
        self.helpButton= QPushButton("Help",self.statusFrame)
        #Create Help button

        

        # Align to left
        self.statusLayout.addWidget(self.labelStatus)
        self.statusLayout.addWidget(self.labelState)

        # Spacer fot the label
        self.statusLayout.addStretch()

        # Añadir el label alineado a la derecha
        self.statusLayout.addWidget(self.labelColor)
        self.statusLayout.addWidget(self.helpButton)
        self.horizontalLayout_15.addWidget(self.countValuesTable)
        self.horizontalLayout_15.addWidget(self.statusFrame)


        self.horizontalLayout_2.addWidget(self.TableFrame)
        


        self.verticalLayout.addWidget(self.CountTableFrame)

                # Asegurar que los botones no se aplasten
        botones = [
            self.startMeasurementButton,
            self.stopMeasurementButton,
            self.channelAClearButton,
            self.channelBClearButton,
            self.channelCClearButton,
            self.channelDClearButton,
            self.saveDataButton,
            self.savePlotsButton,
        ]
        for boton in botones:
            boton.setMinimumHeight(21)
            boton.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.retranslateUi(Form)
        self.comboBoxTimeRange.setMinimumHeight(21)
        self.graphModeComboBox.setMinimumHeight(21)
        self.ChannelACountValues.setVisible(False)
        self.ChannelBCountValues.setVisible(False)
        self.ChannelCCountValues.setVisible(False)
        self.ChannelDCountValues.setVisible(False)
        self.setFontSizeToLabels(12,
        self.titleCounts,
        self.channelAValuesCount,
        self.channelBValuesCount,
        self.channelCValuesCount,
        self.channelDValuesCount,
        self.channelAUncertaintyCount,
        self.channelBUncertaintyCount,
        self.channelCUncertaintyCount,
        self.channelDUncertaintyCount,
        self.titleUncertainty
        )
        self.titleCounts.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.titleUncertainty.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelAValuesCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelAUncertaintyCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelBValuesCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelBUncertaintyCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelCValuesCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelCUncertaintyCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelDValuesCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.channelDUncertaintyCount.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        
        self.verticalLayout_3.setSpacing(2)  # Espacio vertical entre filas
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)  # Márgenes del layout general
        
        # Channel A
        left, _, right, _ = self.horizontalLayout_11.getContentsMargins()
        self.horizontalLayout_11.setContentsMargins(left, 0, right, 0)

        # Channel B
        left, _, right, _ = self.horizontalLayout_12.getContentsMargins()
        self.horizontalLayout_12.setContentsMargins(left, 0, right, 0)

        # Channel C
        left, _, right, _ = self.horizontalLayout_13.getContentsMargins()
        self.horizontalLayout_13.setContentsMargins(left, 0, right, 0)

        # Channel D
        left, _, right, _ = self.horizontalLayout_14.getContentsMargins()
        self.horizontalLayout_14.setContentsMargins(left, 0, right, 0)
        
        #Title
        left, top, right, _ = self.horizontalLayout_14.getContentsMargins()
        self.horizontalLayout_10.setContentsMargins(left, top, right, 0)
        

        QMetaObject.connectSlotsByName(Form)
        self.drawColorPoint()

        # ── Explicit Tab order ───────────────────────────────────────────
        # Same class of bug as in the other measurement tabs: Start/Stop
        # (startMeasurementButton/stopMeasurementButton) are *created*
        # right after the channel checkboxes, but only *added* to
        # verticalLayout_2 at the very end — after Graph mode, Detached
        # options, Time range, and the per-channel Clear buttons — so
        # they render near the bottom, just above Save Data/Save Plots.
        # Left to Qt's default (creation-order) focus chain, Tab from the
        # last channel checkbox jumped straight down to Start/Stop before
        # ever reaching the Graph/Detached/Time range/Clear controls in
        # between. Chain everything explicitly to match the real
        # on-screen order.
        QWidget.setTabOrder(self.channelACheckBox, self.channelBCheckBox)
        QWidget.setTabOrder(self.channelBCheckBox, self.channelCCheckBox)
        QWidget.setTabOrder(self.channelCCheckBox, self.channelDCheckBox)
        QWidget.setTabOrder(self.channelDCheckBox, self.comboBoxTimeRange)
        QWidget.setTabOrder(self.comboBoxTimeRange, self.graphModeComboBox)
        QWidget.setTabOrder(self.graphModeComboBox, self.tableCheckBox)
        QWidget.setTabOrder(self.tableCheckBox, self.labelCheckBox)
        QWidget.setTabOrder(self.labelCheckBox, self.channelAClearButton)
        QWidget.setTabOrder(self.channelAClearButton, self.channelBClearButton)
        QWidget.setTabOrder(self.channelBClearButton, self.channelCClearButton)
        QWidget.setTabOrder(self.channelCClearButton, self.channelDClearButton)
        QWidget.setTabOrder(self.channelDClearButton, self.startMeasurementButton)
        QWidget.setTabOrder(self.startMeasurementButton, self.stopMeasurementButton)
        QWidget.setTabOrder(self.stopMeasurementButton, self.saveDataButton)
        QWidget.setTabOrder(self.saveDataButton, self.savePlotsButton)
        QWidget.setTabOrder(self.savePlotsButton, self.countValuesTable)
        QWidget.setTabOrder(self.countValuesTable, self.helpButton)
    # setupUi

    def retranslateUi(self, Form):
        """
        Sets the visible text of every widget created in setupUi:
        channel labels/checkboxes, buttons, combo box items, and the
        counts table's column headers (Time, A, B, C, D in bold).

        Also sets the default state of the graph display mode radio
        buttons (separate graphics selected by default).

        :param Form: The QWidget/QDialog whose widgets are being labeled.
        :return: None
        """
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.channelLabel.setText(QCoreApplication.translate("Form", u"Channels:", None))
        self.channelACheckBox.setText(QCoreApplication.translate("Form", u"A", None))
        self.channelBCheckBox.setText(QCoreApplication.translate("Form", u"B", None))
        self.channelCCheckBox.setText(QCoreApplication.translate("Form", u"C", None))
        self.channelDCheckBox.setText(QCoreApplication.translate("Form", u"D", None))
        self.startMeasurementButton.setText(QCoreApplication.translate("Form", u"Start", None))
        self.stopMeasurementButton.setText(QCoreApplication.translate("Form", u"Stop", None))
        self.graphLabel.setText(QCoreApplication.translate("Form", u"Graph:", None))
        self.graphModeComboBox.setItemText(0, QCoreApplication.translate("Form", u"Merge", None))
        self.graphModeComboBox.setItemText(1, QCoreApplication.translate("Form", u"Separate", None))
        self.graphModeComboBox.setItemText(2, QCoreApplication.translate("Form", u"Detached", None))
        self.timeRangeLabel.setText(QCoreApplication.translate("Form", u"Time range:", None))
        self.comboBoxTimeRange.setItemText(0, QCoreApplication.translate("Form", u"10 seconds", None))
        self.comboBoxTimeRange.setItemText(1, QCoreApplication.translate("Form", u"20 seconds", None))
        self.comboBoxTimeRange.setItemText(2, QCoreApplication.translate("Form", u"50 seconds", None))
        self.comboBoxTimeRange.setItemText(3, QCoreApplication.translate("Form", u"100 seconds", None))
        self.comboBoxTimeRange.setItemText(4, QCoreApplication.translate("Form", u"200 seconds", None))
        self.comboBoxTimeRange.setItemText(5, QCoreApplication.translate("Form", u"500 seconds", None))
        self.comboBoxTimeRange.setItemText(6, QCoreApplication.translate("Form", u"1000 seconds", None))
        self.comboBoxTimeRange.setItemText(7, QCoreApplication.translate("Form", u"Full range", None))
        self.comboBoxTimeRange.setItemText(8, QCoreApplication.translate("Form", u"Free navigation", None))

        self.clearLabel.setText(QCoreApplication.translate("Form", u"Clear data channels:", None))
        self.channelAClearButton.setText(QCoreApplication.translate("Form", u"A", None))
        self.channelBClearButton.setText(QCoreApplication.translate("Form", u"B", None))
        self.channelCClearButton.setText(QCoreApplication.translate("Form", u"C", None))
        self.channelDClearButton.setText(QCoreApplication.translate("Form", u"D", None))
        self.saveDataButton.setText(QCoreApplication.translate("Form", u"Save Data File", None))
        self.savePlotsButton.setText(QCoreApplication.translate("Form", u"Save Plots", None))
        self.titleCounts.setText(QCoreApplication.translate("Form", u" <b>Est. counts (cps)<\b>", None))
        self.titleUncertainty.setText(QCoreApplication.translate("Form", u"<b>Uncertainty<\b>", None))
        self.channelAValuesCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        self.channelAUncertaintyCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        self.channelBValuesCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        self.channelBUncertaintyCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        self.channelCValuesCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        self.channelCUncertaintyCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        self.channelDValuesCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        self.channelDUncertaintyCount.setText(QCoreApplication.translate("Form", u"Not estimated yet", None))
        font_bold = QFont()
        font_bold.setBold(True)

        ___qtablewidgetitem = QTableWidgetItem()
        ___qtablewidgetitem.setText(QCoreApplication.translate("Form", u"Time", None))
        ___qtablewidgetitem.setFont(font_bold)
        self.countValuesTable.setHorizontalHeaderItem(0, ___qtablewidgetitem)

        ___qtablewidgetitem1 = QTableWidgetItem()
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Form", u"A", None))
        ___qtablewidgetitem1.setFont(font_bold)
        self.countValuesTable.setHorizontalHeaderItem(1, ___qtablewidgetitem1)

        ___qtablewidgetitem2 = QTableWidgetItem()
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Form", u"B", None))
        ___qtablewidgetitem2.setFont(font_bold)
        self.countValuesTable.setHorizontalHeaderItem(2, ___qtablewidgetitem2)

        ___qtablewidgetitem3 = QTableWidgetItem()
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Form", u"C", None))
        ___qtablewidgetitem3.setFont(font_bold)
        self.countValuesTable.setHorizontalHeaderItem(3, ___qtablewidgetitem3)

        ___qtablewidgetitem4 = QTableWidgetItem()
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Form", u"D", None))
        ___qtablewidgetitem4.setFont(font_bold)
        self.countValuesTable.setHorizontalHeaderItem(4, ___qtablewidgetitem4)
        self.graphModeComboBox.setCurrentIndex(1)  # Default to "Separate" graphics mode
    # retranslateUi
    def drawColorPoint(self):
        """
        Draws a small gray circle on labelColor as the initial (idle)
        status indicator, before any measurement colors it.

        :return: None
        """
        pixmap = QPixmap(self.labelColor.size())
        pixmap.fill(Qt.transparent)  

        painter = QPainter(pixmap)
        painter.setRenderHint(QPainter.Antialiasing) 
        painter.setBrush(QColor(128, 128, 128))  
        painter.setPen(Qt.NoPen)

        # Definir el tamaño del punto (círculo)
        point_size = min(self.labelColor.width(), self.labelColor.height()) // 2

        # Calcular la posición del círculo para que quede centrado
        x = (self.labelColor.width() - point_size) // 2
        y = (self.labelColor.height() - point_size) // 2

        painter.drawEllipse(x, y, point_size, point_size)
        painter.end()
        self.labelColor.setPixmap(pixmap)
    
    def setFontSizeToLabels(self,size, *labels):
        """
        Applies the same point size to any number of QLabel widgets.

        :param size: Font point size to apply.
        :param labels: One or more QLabel widgets to resize.
        :return: None
        """
        font = QFont()
        font.setPointSize(size)
        for label in labels:
            label.setFont(font)