import os
import pathlib
from datetime import datetime
import json
from pathlib import Path
from platformdirs import user_config_dir



#Create the folder
class createsavefile:
    def __init__(self):
        self.app_name = "TempicoSoftware"  
        self.config_dir = Path(user_config_dir(self.app_name))
        self.config_dir.mkdir(parents=True, exist_ok=True)
    
    
    def createDefaultFolder(self):
        save_path = self.config_dir / "SaveFileConstants.json"
        if not save_path.exists():
            default_data = {
                "saveFolder": "",
                "startStopHistogramPrefix": "StartStopHistogram",
                "lifetimePrefix": "Lifetime",
                "countsEstimationPrefix": "CountsEstimation",
                "timeStampingPrefix": "TimeStamping"
            }
            with open(save_path, "w", encoding="utf-8") as f:
                json.dump(default_data, f, indent=4, ensure_ascii=False)

        with open(save_path, "r", encoding="utf-8") as file:
            data = json.load(file)

        if not data.get("saveFolder") or not os.path.exists(data["saveFolder"]):
            data["saveFolder"] = ""
            with open(save_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=4, ensure_ascii=False)
            self.create_folder_and_file()
        self.createTempFileData()
    def getPathFolder(self):
        return self.config_dir/"SaveFileConstants.json"
    
    def getExistenceCurrentFolder(self, data):
        folderPath=data['saveFolder']
        return os.path.isdir(folderPath)
    
    def createReadmeFile(self, folderPath):
        readme_path = Path(folderPath) / "README(IMPORTANT!).txt"
        if not readme_path.exists():
            readme_text = (
                "This folder contains AutoSaveData.txt, which stores the most recent "
                "measurement data generated by the automatic save feature.\n\n"
                "IMPORTANT:\n"
                "- These data are overwritten each time a new measurement starts. "
                "Once overwritten, the previous data cannot be recovered.\n"
                "- Open this file **only** if you experience a problem with your last measurement.\n"
                "- If you need to keep these data, copy the content of AutoSaveData.txt "
                "to a safe location before starting a new measurement.\n\n"
                "WARNING DURING MEASUREMENT:\n"
                "- Do NOT open AutoSaveData.txt while a measurement is running. "
                "Opening or editing the file during data acquisition may cause the program to fail."
            )
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(readme_text)
    
    def createTempFileData(self):
        dataFolderDict = self.getDataFolderPrefix()
        currentFolder = dataFolderDict['saveFolder']
        folderName = "TempData"
        fileData = "AutoSaveData.txt"
        folderPath = os.path.join(currentFolder, folderName)
        filePath   = os.path.join(folderPath, fileData)

        os.makedirs(folderPath, exist_ok=True)

        with open(filePath, "w", encoding="utf-8") as f:
            pass

        self.createReadmeFile(folderPath)
    
    
    def clearDataAutoSave(self):
        dataFolderDict = self.getDataFolderPrefix()
        currentFolder  = dataFolderDict['saveFolder']
        folderName     = "TempData"
        fileData       = "AutoSaveData.txt"
        folderPath = os.path.join(currentFolder, folderName)
        filePath   = os.path.join(folderPath, fileData)
        with open(filePath, "w", encoding="utf-8") as f:
            f.truncate(0)

        self.createReadmeFile(folderPath)
    
    def getAutoSaveDataPath(self):
        dataFolderDict = self.getDataFolderPrefix()
        currentFolder  = dataFolderDict['saveFolder']
        folderName     = "TempData"
        fileData       = "AutoSaveData.txt"
        filePath = os.path.join(currentFolder, folderName, fileData)
        return filePath
            
    def getAutoSaveFolderPath(self):
        dataFolderDict = self.getDataFolderPrefix()
        currentFolder  = dataFolderDict['saveFolder']
        folderName     = "TempData"
        folderPath = os.path.join(currentFolder, folderName)
        return folderPath
          
        
    
    def getDataFolderPrefix(self):
        pathConstants=self.getPathFolder()
        with open(pathConstants,"r",encoding="utf-8") as file:
            data = json.load(file)
        dataDict={}
        documents_folder = os.path.join(os.path.expanduser("~"), "Documents")
        default_save_folder = os.path.join(documents_folder, "TempicoSoftwareData")
        existFolder=self.getExistenceCurrentFolder(data)
        if not existFolder:
           data['saveFolder']=""
        if data['saveFolder']=="":
            self.create_folder_and_file()
            dataDict['saveFolder']= default_save_folder
            self.changeFolder(default_save_folder)
        else:
            dataDict['saveFolder']= data['saveFolder']
        dataDict['startStopHistogramPrefix']= data['startStopHistogramPrefix']
        dataDict['lifetimePrefix']= data['lifetimePrefix']
        dataDict['countsEstimationPrefix']= data['countsEstimationPrefix']
        dataDict['timeStampingPrefix']= data['timeStampingPrefix'] 
        return dataDict
    
    
    
    def changePrefix(self,tab, newPrefix):
        pathConstants=self.getPathFolder()
        with open(pathConstants,"r",encoding="utf-8") as file:
            data = json.load(file)
        if tab=="startStopHistogram":
            data["startStopHistogramPrefix"]= newPrefix
        elif tab=="Lifetime":
            data["lifetimePrefix"]= newPrefix
        elif tab=="CountsEstimated":
            data["countsEstimationPrefix"]= newPrefix
        elif tab=="TimeStamping":
            data["timeStampingPrefix"]= newPrefix
        with open(pathConstants, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=4, ensure_ascii=False)
    
    def changeFolder(self, newPath):
        pathConstants=self.getPathFolder()
        with open(pathConstants,"r",encoding="utf-8") as file:
            data = json.load(file)
        data["saveFolder"]= newPath
        with open(pathConstants, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=4, ensure_ascii=False)
        

    def create_folder_and_file(self):
        """
        Creates a folder named 'TempicoSoftwareData' inside the user's 'Documents' directory, 
        and creates a file named 'data_constants.txt' (or '.data_constants.txt' on Unix-based systems) inside that folder. 
        The file is populated with predefined default values for histogram and data names. 
        The file is hidden depending on the operating system.

        The folder and file are created with the following details:
        - Folder path: <Documents>/TempicoSoftwareData
        - File name: data_constants.txt (or '.data_constants.txt' for Unix-based systems)
        - The file contains the following default data:
        - Folder Path
        - Default Histogram Name
        - Default g2 Name
        - Default Lifetime Name

        In case of a Windows system, the file is made hidden using the Windows API. For Unix-based systems (Linux, macOS), 
        the file is renamed to be hidden by adding a dot ('.') before the filename.

        :raises OSError: If an error occurs during folder or file creation, or when accessing the filesystem.
        :returns: None
        """
        documents_dir = os.path.join(pathlib.Path.home(), "Documents")
        folder_name = "TempicoSoftwareData"
        folder_path = os.path.join(documents_dir, folder_name)

        try:
            os.makedirs(folder_path, exist_ok=True)

        except OSError as e:
            print(f"Error occurred while creating the folder and/or file: {e}")
            

    #Check if the folder already exist 

    def check_folder_and_file(self):
        """
        Checks whether the folder 'TempicoSoftwareData' and the file 'data_constants.txt' 
        exist in the user's 'Documents' directory.

        The function constructs the paths for both the folder and the file, and checks if both exist:
        - Folder path: <Documents>/TempicoSoftwareData
        - File name: data_constants.txt

        If both the folder and the file exist, the function returns True. Otherwise, it returns False.

        :returns: bool: True if the folder and file exist, False otherwise.
        """
        documents_dir = os.path.join(pathlib.Path.home(), "Documents")
        folder_name = "TempicoSoftwareData"
        file_name = "data_constants.txt"
        folder_path = os.path.join(documents_dir, folder_name)
        file_path = os.path.join(folder_path, file_name)
        valor=False

        if os.path.exists(folder_path) and os.path.exists(file_path):
            valor= True
        
        return valor

    #Create the folder

    def create_folder(self):
        """
        Checks if the specified folder and file already exist. If they do exist, it creates 
        the folder and file by calling the 'create_folder_and_file' function.

        :returns: None
        """
        value=self.check_folder_and_file()
        if value:
            self.create_folder_and_file()
            
    #Get the dictionary with the constants
        
    def read_default_data(self):
        """
        Reads the default data from the file 'data_constants.txt' located in the 
        'TempicoSoftwareData' folder inside the user's 'Documents' directory.

        This function attempts to read the file line by line and extracts key-value pairs 
        formatted as "key: value". The first line, which contains the folder path, is 
        processed separately. The extracted key-value pairs are stored in a dictionary, 
        which is returned as the output.

        If the file is not found or an error occurs while reading the file, the function
        returns None.

        :returns: dict or None: A dictionary containing the data from the file, or None if 
                an error occurred.
        """
        # Get the path to the "Documents" directory on the current operating system
        documents_dir = os.path.join(pathlib.Path.home(), "Documents")

        # Specify the folder name and file name
        folder_name = "TempicoSoftwareData"
        if os.name == 'posix':  
            file_name = ".data_constants.txt"
        else:  
            file_name = "data_constants.txt"

        # Construct the full path to the file
        file_path = os.path.join(documents_dir, folder_name, file_name)

        try:
            data_dict = {}

            # Open the file in read mode
            with open(file_path, "r") as file:
                # Read each line of the file
                number=0
                for line in file:
                    # Split the line into key and value (assuming it's in the format "key: value")
                    if number==0:
                        key,value= 'Folder path',line.split(': ')[1].replace('\n','')
                        data_dict[key]=value
                        number=1
                    key_value = line.strip().split(":")
                    if len(key_value) == 2:
                        key, value = key_value[0].strip(), key_value[1].strip()
                        data_dict[key] = value
            file.close()

            return data_dict

        except FileNotFoundError:
            print(f"The file '{file_path}' was not found.")
            return None
        except Exception as e:
            print(f"Error while reading the file '{file_path}': {e}")
            return None

    #Save the files in a txt files in the folder created
    def save_lists_as_columns_txt(self,data_lists, file_names, column_names, path,settings, extension):
        """
        Saves multiple lists of data as separate text files, where each list is written as a 
        column in the text file. The files are saved in the specified directory with the 
        provided file names, and the columns are named based on the given column names. 

        This function ensures that the specified directory exists, and raises an error if 
        the lengths of the input lists do not match.

        :param data_lists: A list of lists, where each list contains the data to be written to a file (list).
        :param file_names: A list of strings specifying the names of the output files (list of str).
        :param column_names: A list of strings specifying the names of the columns in the text files (list of str).
        :param path: The directory path where the files will be saved (str).
        :param settings: A list of settings to be written as the first line in each file (list of str).
        :param extension: The file extension for the output files (str).
        :raises ValueError: If the lengths of data_lists, file_names, and column_names do not match.
        :returns: None
        """
        if extension=="csv":
            newSettings=[]
            for setting in settings:
                newSetting=setting.replace("\t",";")
                newSettings.append(newSetting)
            settings=newSettings
                
            
        if not os.path.exists(path):
            os.makedirs(path)
            
        if len(data_lists) != len(file_names) or len(data_lists) != len(column_names):
            raise ValueError("Data lists, file names, and column names must have the same length.")
            
        for file_name, data_list, column_name,setting_channel in zip(file_names, data_lists, column_names,settings):
            full_file_path = os.path.join(path, f"{file_name}."+str(extension))
            
            with open(full_file_path, 'w') as file:
                file.write(f"{setting_channel}\n")
                file.write(f"{column_name}\n")
                for element in data_list:
                    file.write(f"{element}\n")
                file.close()
                
    def save_g2_data(self,data, file_name, folder_path, settings, extension, textLabel):
        """
        Saves g2 data (tau and g2 values) into a text file in a specified folder. The function
        ensures that the provided tau and g2 values have the same length and writes them into 
        a file along with specified settings and a label for the g2 values.

        The file is saved in the specified folder path, with the provided file name and extension.

        :param data: A tuple where the first element is a list of tau values and the second 
                    element is a list of corresponding g2 values (tuple of lists).
        :param file_name: The name of the output file (str).
        :param folder_path: The path to the folder where the file will be saved (str).
        :param settings: A string representing the settings to be written in the first line of the file (str).
        :param extension: The file extension for the output file (str).
        :param textLabel: A label to be written before the g2 values in the file (str).
        :raises ValueError: If the lengths of the tau and g2 value lists do not match.
        :returns: None
        """
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
        
        if len(data[0]) != len(data[1]):
            raise ValueError("Tau and g2 Values must have the same length")
        else:
        
            full_path = os.path.join(folder_path, f"{file_name}.{extension}")
            
            with open(full_path, 'w') as file:
                file.write(settings + '\n')
                
                file.write(textLabel+"\tg2 Values\n")
                
                for tau, g2_value in zip(data[0], data[1]):
                    file.write(f"{tau}\t{g2_value}\n")
                    
    def save_LifeTime_data(self,data, file_name, folder_path, settings, extension, textLabel):
        """
        Saves LifeTime data (time and LifeTime values) into a text file in a specified folder. The function
        ensures that the provided time and LifeTime values have the same length and writes them into 
        a file along with specified settings and a label for the LifeTime values.

        The file is saved in the specified folder path, with the provided file name and extension.

        :param data: A tuple where the first element is a list of time values and the second 
                    element is a list of corresponding LifeTime values (tuple of lists).
        :param file_name: The name of the output file (str).
        :param folder_path: The path to the folder where the file will be saved (str).
        :param settings: A string representing the settings to be written in the first line of the file (str).
        :param extension: The file extension for the output file (str).
        :param textLabel: A label to be written before the LifeTime values in the file (str).
        :raises ValueError: If the lengths of the time and LifeTime value lists do not match.
        :returns: None
        """
        if extension=="txt" or extension=="dat":
            separator="\t"
        else:
            separator=";"
            settings=settings.replace("\t",";")
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
        
        if len(data[0]) != len(data[1]):
            raise ValueError("Time and LifeTime Values must have the same length")
        else:
        
            full_path = os.path.join(folder_path, f"{file_name}.{extension}")
            
            with open(full_path, 'w') as file:
                file.write(settings + '\n')
                
                file.write(f"{textLabel}{separator}Counts LifeTime\n")
                
                for tau, LifeTimeValue in zip(data[0], data[1]):
                    file.write(f"{tau}{separator}{LifeTimeValue}\n")
    def save_counts_data(self,time_stamp,data,dataUncertainties,filenames,folder_path,settings, extension,channels):
        if extension=="txt" or extension=="dat":
            separator="\t"
        else:
            separator=";"
            newSettings=[]
            for setting in settings:
                newSetting=setting.replace("\t",";")
                newSettings.append(newSetting)
            settings=newSettings
            
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
        if len(time_stamp)!= len(data):
            raise ValueError("Time stamps and measurement must have the same lenght")
        else:
            for file_name,timeStamp, data_list,data_uncertainties,setting_channel, channel in zip(filenames,time_stamp, data,dataUncertainties,settings,channels):
                full_path=os.path.join(folder_path, f"{file_name}.{extension}")
                
                with open(full_path, 'w') as file:
                    file.write(setting_channel + '\n')
                    file.write(f"Time (HH:MM:SS) {separator} Counts Channel {channel}(counts/sec) {separator} Uncertainties Channel {channel}(counts/sec) {separator} Mean time interval (us) {separator} Uncertainty mean time interval (us)\n")
                    for timeStamp, countValue,uncertanty in zip(timeStamp,data_list,data_uncertainties):
                        valueFormated= f"{countValue:.5f}"
                        timeValue=(1/float(countValue))*(10**6)
                        uncertaintyFormated=f"{uncertanty:.5f}"
                        timeFormated=f"{timeValue:.5f}"
                        uncertaintyTime=(float(uncertanty)/(float(countValue)**2))*(10**6)
                        uncertaintyTimeFormated= f"{uncertaintyTime:.5f}"
                        file.write(f"{timeStamp}{separator}{valueFormated}{separator}{uncertaintyFormated}{separator}{timeFormated}{separator}{uncertaintyTimeFormated}\n")

    def save_time_stamp_autosave(self, startValues, stopValues, channels, settings):
        channelList = ["Start", "A", "B", "C", "D"]
        folderPath=self.getAutoSaveFolderPath()
        if not os.path.exists(folderPath):
            os.makedirs(folderPath)

        if len(startValues) != len(stopValues) or len(stopValues) != len(channels):
            raise ValueError("Start times, stop times and channels list must have the same length")
        filePath=self.getAutoSaveDataPath()

        # Verificar si el archivo existe Y está vacío
        archivo_vacio = not os.path.exists(filePath) or os.path.getsize(filePath) == 0

        with open(filePath, 'a') as file:
            if archivo_vacio:
                file.write(settings)
                file.write("Start Time (YY:MM:DD:HH:MM:SS)\tStop Time (ps)\tChannel\n")
            for startTime, stopTime, channel in zip(startValues, stopValues, channels):
                file.write(f"{startTime}\t{stopTime}\t{channelList[channel]}\n")
        
    
    
    def save_time_stamp(self, startValues, stopValues, channels, filename, folder_path, extension, settings):
        if extension=="csv":
            settings=settings.replace("\t",";")
            separator=";"
        else:
            separator="\t"
            
        channelList = ["Start", "A", "B", "C", "D"]

        if not os.path.exists(folder_path):
            os.makedirs(folder_path)

        if len(startValues) != len(stopValues) or len(stopValues) != len(channels):
            raise ValueError("Start times, stop times and channels list must have the same length")

        full_path = os.path.join(folder_path, f"{filename}.{extension}")

        file_exists = os.path.isfile(full_path)

        
        with open(full_path, 'a') as file:    
            if not file_exists:
                file.write(settings)
                file.write(f"Start Time (YY:MM:DD:HH:MM:SS){separator}Stop Time (ps){separator}Channel\n")
            for startTime, stopTime, channel in zip(startValues, stopValues, channels):
                file.write(f"{startTime}{separator}{stopTime}{separator}{channelList[channel]}\n")
    
    def sort_time_stamps(self, file_path,autoSave):
        if autoSave:
            originalPath = os.path.join("./TempData", f"AutoSaveData.txt")
        else:
            originalPath = file_path
            
        with open(originalPath, 'r', encoding='utf-8') as file:
            lines = file.readlines()

        if not lines:
            return

        header = lines[6]
        data_lines = lines[7:]

        parsed_data = []
        for line in data_lines:
            parts = line.strip().split('\t')
            if len(parts) == 3:
                start_time_str, stop_time, channel = parts
                try:
                    start_time = datetime.strptime(start_time_str, "%Y-%m-%d %H:%M:%S.%f")
                    parsed_data.append((start_time, stop_time, channel))
                except ValueError:
                    continue  # Skip malformed lines
        extension=file_path.split(".")[-1]
        if extension=="csv":
            separator=";"
        else:
            separator="\t"
        #replace separator header
        newHeader=[]
        for lineSettings in header:
            newLineSettings=lineSettings.replace("\t",separator)
            newHeader.append(newLineSettings)
        header=newLineSettings
        sorted_data = sorted(parsed_data, key=lambda x: x[0])

        with open(file_path, 'w', encoding='utf-8') as file:
            file.write(header)
            for start_time, stop_time, channel in sorted_data:
                file.write(f"{start_time.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}{separator}{stop_time}{separator}{channel}\n")
    
    def convertFileFormat(self, file_path, new_extension, autoSaved):
        if autoSaved:
            originalPath = os.path.join("./TempData", "AutoSaveData.txt")
        else:
            originalPath = file_path

        current_ext = originalPath.split(".")[-1].lower()
        base_path = ".".join(file_path.split(".")[:-1])
        new_file_path = base_path + "." + new_extension.lower()

        if not autoSaved:
            if current_ext == "csv":
                current_sep = ";"
            else:
                current_sep = "\t"
        else:
            current_sep = "\t"

        if new_extension.lower() == "csv":
            new_sep = ";"
        else:
            new_sep = "\t"

        os.makedirs(os.path.dirname(new_file_path), exist_ok=True)

        with open(originalPath, 'r', encoding='utf-8') as infile, \
            open(new_file_path, 'w', encoding='utf-8') as outfile:

            for i in range(8):
                line = infile.readline()
                if not line:
                    break
                if new_extension.lower() == "csv":
                    outfile.write(line.replace("\t", ";"))
                else:
                    outfile.write(line.replace(";", "\t"))

            
            for line in infile:
                if current_sep != new_sep:
                    parts = line.strip().split(current_sep)
                    outfile.write(new_sep.join(parts) + "\n")
                else:
                    outfile.write(line)
    
    def convertFileFromOldFile(self, file_path, new_folder, new_extension):
        if not os.path.exists(file_path):
            return False

        os.makedirs(new_folder, exist_ok=True)

        file_name = os.path.basename(file_path)
        base_name = ".".join(file_name.split(".")[:-1])
        current_ext = file_path.split(".")[-1].lower()
        new_file_name = base_name + "." + new_extension.lower()
        new_file_path = os.path.join(new_folder, new_file_name)

        if current_ext == "csv":
            current_sep = ";"
        else:
            current_sep = "\t"

        if new_extension.lower() == "csv":
            new_sep = ";"
        else:
            new_sep = "\t"

        with open(file_path, 'r', encoding='utf-8') as infile, \
            open(new_file_path, 'w', encoding='utf-8') as outfile:

            for i in range(8):
                line = infile.readline()
                if not line:
                    break
                if current_sep != new_sep:
                    outfile.write(line.replace(current_sep, new_sep))
                else:
                    outfile.write(line)


            for line in infile:
                if current_sep != new_sep:
                    parts = line.strip().split(current_sep)
                    outfile.write(new_sep.join(parts) + "\n")
                else:
                    outfile.write(line)

        return True
                
    